-- AMI customization: projects, Tender / In Hand pipelines, CR numbers,
-- line items and CR revisions on deals (opportunities).

create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "end_client" text,
    "consultant" text,
    "location" text,
    "sector" text,
    "estimated_value" bigint,
    "description" text,
    "sales_id" bigint,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."projects" enable row level security;

alter table "public"."projects" add constraint "projects_pkey" primary key ("id");

alter table "public"."projects"
    add constraint "projects_sales_id_fkey" foreign key ("sales_id") references "public"."sales"("id");

create sequence "public"."deals_cr_number_seq";

-- Existing deals each get their own CR number from the column default.
alter table "public"."deals"
    add column "project_id" bigint,
    add column "pipeline" text not null default 'tender',
    add column "cr_number" text not null default ('CR-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.deals_cr_number_seq')::text, 4, '0')),
    add column "line_items" jsonb not null default '[]'::jsonb,
    add column "revisions" jsonb not null default '[]'::jsonb;

alter table "public"."deals"
    add constraint "deals_project_id_fkey" foreign key ("project_id") references "public"."projects"("id") on update cascade on delete set null;

alter table "public"."deals" add constraint "deals_cr_number_key" unique ("cr_number");

alter table "public"."deals"
    add constraint "deals_pipeline_check" check ("pipeline" in ('tender', 'in_hand'));

create index "deals_project_id_idx" on "public"."deals" using btree ("project_id");

CREATE OR REPLACE FUNCTION "public"."keep_deal_cr_number"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
BEGIN
  -- The CR number identifies the quotation for the deal's whole life
  NEW.cr_number := OLD.cr_number;
  RETURN NEW;
END;
$$;

create or replace trigger "set_project_sales_id_trigger"
    before insert on "public"."projects"
    for each row execute function "public"."set_sales_id_default"();

create or replace trigger "keep_deal_cr_number_trigger"
    before update of "cr_number" on "public"."deals"
    for each row execute function "public"."keep_deal_cr_number"();

create policy "Enable read access for authenticated users" on "public"."projects" for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on "public"."projects" for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on "public"."projects" for update to authenticated using (true) with check (true);
create policy "Projects Delete Policy" on "public"."projects" for delete to authenticated using (true);

grant all on table "public"."projects" to "anon";
grant all on table "public"."projects" to "authenticated";
grant all on table "public"."projects" to "service_role";

grant all on sequence "public"."projects_id_seq" to "anon";
grant all on sequence "public"."projects_id_seq" to "authenticated";
grant all on sequence "public"."projects_id_seq" to "service_role";

grant all on sequence "public"."deals_cr_number_seq" to "anon";
grant all on sequence "public"."deals_cr_number_seq" to "authenticated";
grant all on sequence "public"."deals_cr_number_seq" to "service_role";
